# -*- coding: utf-8 -*-
"""UTS_DATA_MINING_23.11.5665.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zZhNaaOmBgES-oW7R4r_B2wLctY4FV-S

# **Gamification_KMeans_Clustering**

# **Instalasi Library yang Dibutuhkan**
"""

!pip install kaggle opendatasets -q
!pip install yellowbrick -q

print("Instalasi selesai!")

"""# **Import Library**"""

import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
from matplotlib.colors import ListedColormap

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.decomposition import PCA
from sklearn.metrics import (
    davies_bouldin_score,
    silhouette_score,
    silhouette_samples,
    calinski_harabasz_score
)
from sklearn.pipeline import Pipeline

from scipy import stats
from scipy.stats import f_oneway, kruskal

import os
import json

RANDOM_STATE = 42
np.random.seed(RANDOM_STATE)

plt.style.use('seaborn-v0_8-whitegrid')
sns.set_palette('husl')

print("Semua library berhasil diimport!")
print(f"\nLibrary Versi:")
print(f"  NumPy    : {np.__version__}")
print(f"  Pandas   : {pd.__version__}")
import sklearn
print(f"  Sklearn  : {sklearn.__version__}")

"""# **Download Dataset**"""

import subprocess

print("Downloading Dataset 1: Predict Online Course Engagement...")
!kaggle datasets download -d rabieelkharoua/predict-online-course-engagement-dataset --unzip -p /content/data/

print("\nDownloading Dataset 2: Online Learning Platform Engagement...")
!kaggle datasets download -d bismasajjad/online-learning-platform-engagement-dataset --unzip -p /content/data2/

print("\nFile yang tersedia:")
for root, dirs, files_list in os.walk('/content/data'):
    for file in files_list:
        filepath = os.path.join(root, file)
        size = os.path.getsize(filepath) / 1024
        print(f"   └── {file} ({size:.1f} KB)")

"""## Load & Eksplorasi Dataset (EDA)"""

import glob

csv_files = glob.glob('/content/data/*.csv')
print("File CSV ditemukan:", csv_files)

if csv_files:
    df = pd.read_csv(csv_files[0])
    print(f"\nDataset berhasil dimuat: {csv_files[0]}")
else:
    try:
        df = pd.read_csv('/content/data/online_course_engagement.csv')
    except:
        df = pd.read_csv('/content/data/engagement_data.csv')

print(f"\n Dimensi Dataset: {df.shape[0]:,} baris × {df.shape[1]} kolom")
print(f"\n Kolom-kolom dataset:")
for i, col in enumerate(df.columns, 1):
    print(f"   {i:2d}. {col} ({df[col].dtype})")

print("\n🔍 5 Baris Pertama Dataset:")
df.head()

print("📊 Statistik Deskriptif Dataset:")
df.describe().round(2)

print("=" * 60)
print(" ANALISIS KUALITAS DATA")
print("=" * 60)

missing = df.isnull().sum()
missing_pct = (missing / len(df)) * 100
missing_df = pd.DataFrame({
    'Missing Values': missing,
    'Persentase (%)': missing_pct.round(2)
}).query('`Missing Values` > 0')

if len(missing_df) > 0:
    print(f"\n  Kolom dengan Missing Values:")
    print(missing_df)
else:
    print("\n Tidak ada missing values!")

n_dup = df.duplicated().sum()
print(f"\n Jumlah duplikasi: {n_dup} baris")

print(f"\n Tipe Data:")
print(df.dtypes)

"""## Feature Engineering & Pemilihan Fitur Gamifikasi"""

print("Kolom yang tersedia:")
print(list(df.columns))

print("\n Info Dataset:")
df.info()

df_proc = df.copy()

numeric_cols = df_proc.select_dtypes(include=[np.number]).columns.tolist()
print("Kolom numerik:", numeric_cols)

col_lower = {col.lower().replace(' ', '_'): col for col in df_proc.columns}

time_col = next((v for k, v in col_lower.items() if 'time' in k or 'hour' in k or 'minute' in k), None)
video_col = next((v for k, v in col_lower.items() if 'video' in k), None)
quiz_col = next((v for k, v in col_lower.items() if 'quiz' in k or 'test' in k or 'exam' in k), None)
score_col = next((v for k, v in col_lower.items() if 'score' in k or 'grade' in k or 'point' in k), None)
completion_col = next((v for k, v in col_lower.items() if 'complet' in k or 'progress' in k), None)
forum_col = next((v for k, v in col_lower.items() if 'forum' in k or 'discussion' in k or 'participat' in k), None)

print(f"\n🔍 Kolom terdeteksi:")
print(f"  Waktu belajar  : {time_col}")
print(f"  Video ditonton : {video_col}")
print(f"  Kuis           : {quiz_col}")
print(f"  Skor           : {score_col}")
print(f"  Completion     : {completion_col}")
print(f"  Forum          : {forum_col}")

from sklearn.preprocessing import MinMaxScaler

scaler_mm = MinMaxScaler()

features_available = [col for col in [
    time_col, video_col, quiz_col, score_col, completion_col, forum_col
] if col is not None]

if len(features_available) < 3:
    id_cols = [c for c in numeric_cols if 'id' in c.lower()]
    features_available = [c for c in numeric_cols if c not in id_cols][:8]

print(f"\n Fitur yang digunakan untuk clustering:")
for f in features_available:
    print(f"   ✓ {f}")

df_clean = df_proc[features_available].dropna()
print(f"\n Dataset setelah pembersihan: {df_clean.shape[0]:,} baris × {df_clean.shape[1]} kolom")

df_normalized = pd.DataFrame(
    scaler_mm.fit_transform(df_clean),
    columns=features_available
)

print("\n Normalisasi selesai (MinMaxScaler)")
df_normalized.describe().round(3)

df_features = df_normalized.copy()

achievement_cols = [c for c in [score_col, quiz_col, completion_col] if c is not None and c in df_features.columns]
if achievement_cols:
    df_features['Achievement_Score'] = df_features[achievement_cols].mean(axis=1)

activity_cols = [c for c in [time_col, video_col] if c is not None and c in df_features.columns]
if activity_cols:
    df_features['Activity_Score'] = df_features[activity_cols].mean(axis=1)

if forum_col and forum_col in df_features.columns:
    df_features['Social_Score'] = df_features[forum_col]

composite_cols = [c for c in ['Achievement_Score', 'Activity_Score', 'Social_Score']
                  if c in df_features.columns]
if composite_cols:
    df_features['Overall_Engagement'] = df_features[composite_cols].mean(axis=1)

print(" Composite gamification scores berhasil dibuat!")
print("\nKolom features:")
print(df_features.columns.tolist())

"""## Exploratory Data Analysis (EDA) & Visualisasi"""

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle(' Exploratory Data Analysis - Distribusi Fitur Engagement\n& Elemen Gamifikasi',
             fontsize=14, fontweight='bold', y=0.98)

colors = plt.cm.Set2(np.linspace(0, 1, 6))

for idx, (col, ax) in enumerate(zip(features_available[:6], axes.flatten())):
    ax.hist(df_clean[col], bins=30, color=colors[idx], edgecolor='white', alpha=0.8)
    ax.set_title(f'{col}', fontweight='bold')
    ax.set_xlabel('Nilai')
    ax.set_ylabel('Frekuensi')

    ax.axvline(df_clean[col].mean(), color='red', linestyle='--', linewidth=1.5, label=f'Mean: {df_clean[col].mean():.2f}')
    ax.axvline(df_clean[col].median(), color='blue', linestyle='--', linewidth=1.5, label=f'Median: {df_clean[col].median():.2f}')
    ax.legend(fontsize=8)

plt.tight_layout()
plt.savefig('/content/01_EDA_distribusi.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Plot distribusi fitur tersimpan!")

fig, ax = plt.subplots(figsize=(12, 8))

corr_matrix = df_clean.corr()
mask = np.triu(np.ones_like(corr_matrix, dtype=bool))

sns.heatmap(
    corr_matrix,
    annot=True,
    fmt='.3f',
    cmap='RdYlGn',
    center=0,
    square=True,
    linewidths=0.5,
    cbar_kws={'label': 'Koefisien Korelasi'},
    ax=ax
)

ax.set_title(' Correlation Matrix - Fitur Engagement & Gamifikasi',
             fontsize=13, fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig('/content/02_correlation_heatmap.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Correlation heatmap tersimpan!")

fig, ax = plt.subplots(figsize=(14, 6))

df_normalized[features_available].boxplot(
    ax=ax,
    patch_artist=True,
    boxprops=dict(facecolor='lightblue', color='darkblue'),
    medianprops=dict(color='red', linewidth=2),
    whiskerprops=dict(color='darkblue'),
    capprops=dict(color='darkblue'),
    flierprops=dict(marker='o', color='orange', alpha=0.5)
)

ax.set_title(' Distribusi Fitur Setelah Normalisasi (MinMax)',
             fontsize=13, fontweight='bold')
ax.set_ylabel('Nilai Ternormalisasi [0-1]')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('/content/03_boxplot_normalized.png', dpi=150, bbox_inches='tight')
plt.show()

"""## Penentuan Jumlah Cluster Optimal"""

X = df_normalized[features_available].values

k_range = range(2, 11)

results = {
    'k': [],
    'inertia': [],
    'davies_bouldin': [],
    'silhouette': [],
    'calinski_harabasz': []
}

print(" Menghitung metrik evaluasi untuk k=2 hingga k=10...")
print("-" * 65)
print(f"{'k':>4} | {'Inertia':>12} | {'Davies-Bouldin':>14} | {'Silhouette':>10} | {'Calinski-H':>10}")
print("-" * 65)

for k in k_range:
    kmeans = KMeans(
        n_clusters=k,
        init='k-means++',
        n_init=10,
        max_iter=300,
        random_state=RANDOM_STATE
    )
    labels = kmeans.fit_predict(X)

    inertia = kmeans.inertia_
    dbi = davies_bouldin_score(X, labels)
    sil = silhouette_score(X, labels, random_state=RANDOM_STATE)
    ch = calinski_harabasz_score(X, labels)

    results['k'].append(k)
    results['inertia'].append(inertia)
    results['davies_bouldin'].append(dbi)
    results['silhouette'].append(sil)
    results['calinski_harabasz'].append(ch)

    print(f"{k:>4} | {inertia:>12.2f} | {dbi:>14.4f} | {sil:>10.4f} | {ch:>10.2f}")

print("-" * 65)
print("\n Evaluasi selesai!")

results_df = pd.DataFrame(results)

best_dbi_k = results_df.loc[results_df['davies_bouldin'].idxmin(), 'k']
best_sil_k = results_df.loc[results_df['silhouette'].idxmax(), 'k']

print(f"\n Rekomendasi Jumlah Cluster:")
print(f"   Davies-Bouldin Index (min DBI) : k = {best_dbi_k} ")
print(f"   Silhouette Score    (max Sil)  : k = {best_sil_k}")

fig, axes = plt.subplots(2, 2, figsize=(16, 12))
fig.suptitle(' Evaluasi Jumlah Cluster Optimal\nMetode: Elbow, Davies-Bouldin, Silhouette, Calinski-Harabasz',
             fontsize=14, fontweight='bold')

ax1 = axes[0, 0]
ax1.plot(results_df['k'], results_df['inertia'], 'bo-', linewidth=2, markersize=8)
ax1.fill_between(results_df['k'], results_df['inertia'], alpha=0.1, color='blue')
ax1.set_title(' Elbow Method (Inertia / WCSS)', fontweight='bold')
ax1.set_xlabel('Jumlah Cluster (k)')
ax1.set_ylabel('Inertia (Within-Cluster Sum of Squares)')
ax1.set_xticks(results_df['k'])
ax1.grid(True, alpha=0.3)

ax2 = axes[0, 1]
bars = ax2.bar(results_df['k'], results_df['davies_bouldin'],
               color=['#2ecc71' if k == best_dbi_k else '#3498db' for k in results_df['k']],
               edgecolor='white', linewidth=0.5, alpha=0.85)

ax2.plot(results_df['k'], results_df['davies_bouldin'], 'r.-', linewidth=1.5, markersize=10)

min_dbi = results_df['davies_bouldin'].min()
ax2.annotate(f'Optimal\nk={best_dbi_k}\nDBI={min_dbi:.4f}',
             xy=(best_dbi_k, min_dbi),
             xytext=(best_dbi_k + 0.5, min_dbi + 0.05),
             arrowprops=dict(arrowstyle='->', color='red'),
             fontsize=10, color='red', fontweight='bold',
             bbox=dict(boxstyle='round,pad=0.3', facecolor='yellow', alpha=0.8))

ax2.set_title(' Davies-Bouldin Index (Lebih Rendah = Lebih Baik)', fontweight='bold')
ax2.set_xlabel('Jumlah Cluster (k)')
ax2.set_ylabel('Davies-Bouldin Index Score')
ax2.set_xticks(results_df['k'])
ax2.grid(True, alpha=0.3, axis='y')

ax3 = axes[1, 0]
ax3.plot(results_df['k'], results_df['silhouette'], 'gs-', linewidth=2, markersize=8)
ax3.fill_between(results_df['k'], results_df['silhouette'], alpha=0.1, color='green')
best_sil = results_df['silhouette'].max()
ax3.axvline(x=best_sil_k, color='red', linestyle='--', alpha=0.7, label=f'Optimal k={best_sil_k}')
ax3.legend()
ax3.set_title(' Silhouette Score (Lebih Tinggi = Lebih Baik)', fontweight='bold')
ax3.set_xlabel('Jumlah Cluster (k)')
ax3.set_ylabel('Silhouette Score')
ax3.set_xticks(results_df['k'])
ax3.grid(True, alpha=0.3)

ax4 = axes[1, 1]
ax4.plot(results_df['k'], results_df['calinski_harabasz'], 'mp-', linewidth=2, markersize=8)
ax4.fill_between(results_df['k'], results_df['calinski_harabasz'], alpha=0.1, color='purple')
ax4.set_title(' Calinski-Harabasz Score (Lebih Tinggi = Lebih Baik)', fontweight='bold')
ax4.set_xlabel('Jumlah Cluster (k)')
ax4.set_ylabel('Calinski-Harabasz Score')
ax4.set_xticks(results_df['k'])
ax4.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/04_cluster_evaluation.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Plot evaluasi cluster tersimpan!")

"""## K-Means Clustering - Model Final"""

OPTIMAL_K = int(best_dbi_k)
print(f" Jumlah cluster optimal (Davies-Bouldin): k = {OPTIMAL_K}")

kmeans_final = KMeans(
    n_clusters=OPTIMAL_K,
    init='k-means++',
    n_init=20,
    max_iter=500,
    tol=1e-4,
    random_state=RANDOM_STATE,
    algorithm='lloyd'
)

cluster_labels = kmeans_final.fit_predict(X)

df_result = df_clean.copy()
df_result['Cluster'] = cluster_labels
df_result['Cluster_Label'] = cluster_labels

final_dbi = davies_bouldin_score(X, cluster_labels)
final_sil = silhouette_score(X, cluster_labels, random_state=RANDOM_STATE)
final_ch = calinski_harabasz_score(X, cluster_labels)
final_inertia = kmeans_final.inertia_

print("\n" + "=" * 55)
print("        EVALUASI MODEL K-MEANS FINAL")
print("=" * 55)
print(f"  Jumlah Cluster (k)            : {OPTIMAL_K}")
print(f"  Inertia (WCSS)                : {final_inertia:,.2f}")
print(f"  Davies-Bouldin Index (↓ baik) : {final_dbi:.4f}")
print(f"  Silhouette Score (↑ baik)     : {final_sil:.4f}")
print(f"  Calinski-Harabasz (↑ baik)    : {final_ch:.2f}")
print("=" * 55)

print("\n📖 Interpretasi Davies-Bouldin Index:")
if final_dbi < 0.5:
    print("   Sangat Baik (DBI < 0.5): Cluster sangat terpisah dan kompak")
elif final_dbi < 1.0:
    print("   Baik (DBI < 1.0): Cluster cukup terpisah")
elif final_dbi < 1.5:
    print("    Cukup (DBI < 1.5): Cluster agak tumpang tindih")
else:
    print("   Perlu Perbaikan (DBI ≥ 1.5): Cluster banyak tumpang tindih")

print("\n Distribusi Pengguna per Cluster:")
print("-" * 40)

cluster_dist = df_result['Cluster'].value_counts().sort_index()
for cluster_id, count in cluster_dist.items():
    pct = count / len(df_result) * 100
    bar = '█' * int(pct / 2)
    print(f"  Cluster {cluster_id}: {count:5,} pengguna ({pct:.1f}%) {bar}")

print(f"\n  Total: {len(df_result):,} pengguna")

print("\n Rata-rata Fitur per Cluster:")
cluster_means = df_result.groupby('Cluster')[features_available].mean().round(3)
print(cluster_means.to_string())

"""## Profiling & Labeling Cluster Engagement"""

cluster_profile = df_result.groupby('Cluster')[features_available].mean()

cluster_profile['Overall_Engagement'] = cluster_profile.mean(axis=1)

cluster_ranking = cluster_profile['Overall_Engagement'].rank(ascending=False).astype(int)

print(" Profil Rata-rata Fitur per Cluster (setelah normalisasi):")
print(cluster_profile.round(3))
print("\n Ranking Cluster (berdasarkan Overall Engagement):")
print(cluster_ranking)

engagement_labels = {}
label_descriptions = {}

if OPTIMAL_K == 3:
    label_map = {
        cluster_profile['Overall_Engagement'].idxmax(): (' High Engagement',
            'Pengguna aktif dengan skor tinggi pada semua elemen gamifikasi. Sering mengakses platform, menyelesaikan banyak kuis, dan berpartisipasi aktif di forum.'),
        cluster_profile['Overall_Engagement'].idxmin(): (' Low Engagement',
            'Pengguna pasif dengan interaksi minimal. Jarang login, progress kursus rendah, dan hampir tidak berinteraksi dengan elemen gamifikasi.'),
    }
    mid_cluster = [c for c in range(OPTIMAL_K) if c not in label_map][0]
    label_map[mid_cluster] = ('⚡ Medium Engagement',
        'Pengguna moderat yang berinteraksi secara berkala. Menyelesaikan beberapa kuis dan sesekali berpartisipasi di forum.')
    engagement_labels = label_map

elif OPTIMAL_K == 4:
    sorted_clusters = cluster_profile['Overall_Engagement'].sort_values(ascending=False).index.tolist()
    labels_4 = [
        (' Super Active', 'Pengguna paling aktif, memanfaatkan semua fitur gamifikasi secara maksimal'),
        (' Active', 'Pengguna aktif dengan engagement tinggi namun tidak seintensif Super Active'),
        (' Moderate', 'Pengguna dengan tingkat keterlibatan sedang'),
        (' Passive', 'Pengguna pasif dengan interaksi minimal pada platform')
    ]
    engagement_labels = {cluster: (label, desc) for cluster, (label, desc) in zip(sorted_clusters, labels_4)}

else:
    sorted_clusters = cluster_profile['Overall_Engagement'].sort_values(ascending=False).index.tolist()
    level_labels = ['Sangat Tinggi', 'Tinggi', 'Sedang', 'Rendah', 'Sangat Rendah',
                    'Sangat Rendah 2', 'Sangat Rendah 3', 'Sangat Rendah 4', 'Sangat Rendah 5', 'Sangat Rendah 6']
    engagement_labels = {
        cluster: (f'Level {i+1}: {level_labels[i]}', f'Cluster engagement level {i+1}')
        for i, cluster in enumerate(sorted_clusters)
    }

df_result['Engagement_Level'] = df_result['Cluster'].map(
    {k: v[0] for k, v in engagement_labels.items()}
)

print("\n Label Cluster yang Ditetapkan:")
for cluster_id, (label, desc) in engagement_labels.items():
    count = (df_result['Cluster'] == cluster_id).sum()
    pct = count / len(df_result) * 100
    print(f"\n  Cluster {cluster_id} → {label}")
    print(f"  Jumlah: {count:,} pengguna ({pct:.1f}%)")
    print(f"  Deskripsi: {desc}")

"""## Visualisasi Hasil Clustering"""

pca = PCA(n_components=2, random_state=RANDOM_STATE)
X_pca = pca.fit_transform(X)

explained_var = pca.explained_variance_ratio_
print(f"\n PCA Explained Variance:")
print(f"  PC1: {explained_var[0]*100:.1f}%")
print(f"  PC2: {explained_var[1]*100:.1f}%")
print(f"  Total: {sum(explained_var)*100:.1f}%")

fig, axes = plt.subplots(1, 2, figsize=(18, 7))
fig.suptitle(' Hasil K-Means Clustering - Visualisasi PCA\nPengelompokan Tingkat Engagement Pengguna Platform E-Learning',
             fontsize=13, fontweight='bold')

cluster_colors = plt.cm.Set1(np.linspace(0, 0.9, OPTIMAL_K))
color_map = {i: cluster_colors[i] for i in range(OPTIMAL_K)}

ax1 = axes[0]

for cluster_id in range(OPTIMAL_K):
    mask = cluster_labels == cluster_id
    label = engagement_labels.get(cluster_id, (f'Cluster {cluster_id}',))[0]
    ax1.scatter(
        X_pca[mask, 0], X_pca[mask, 1],
        c=[cluster_colors[cluster_id]],
        label=label,
        alpha=0.6,
        s=30,
        edgecolors='white',
        linewidth=0.3
    )

centroids_pca = pca.transform(kmeans_final.cluster_centers_)
ax1.scatter(
    centroids_pca[:, 0], centroids_pca[:, 1],
    c='black', marker='*', s=400,
    zorder=5, label='Centroid'
)

for i, (x, y) in enumerate(centroids_pca):
    ax1.annotate(f'C{i}', (x, y),
                 xytext=(5, 5), textcoords='offset points',
                 fontweight='bold', fontsize=10)

ax1.set_xlabel(f'PC1 ({explained_var[0]*100:.1f}% variance)', fontsize=11)
ax1.set_ylabel(f'PC2 ({explained_var[1]*100:.1f}% variance)', fontsize=11)
ax1.set_title('Visualisasi Cluster (PCA 2D)', fontweight='bold')
ax1.legend(loc='best', fontsize=8, framealpha=0.9)
ax1.grid(True, alpha=0.3)

ax2 = axes[1]

cluster_sizes = []
cluster_labels_plot = []
for cluster_id in range(OPTIMAL_K):
    count = (cluster_labels == cluster_id).sum()
    cluster_sizes.append(count)
    label = engagement_labels.get(cluster_id, (f'Cluster {cluster_id}',))[0]
    cluster_labels_plot.append(f'{label}\n({count:,} pengguna)')

wedges, texts, autotexts = ax2.pie(
    cluster_sizes,
    labels=cluster_labels_plot,
    autopct='%1.1f%%',
    colors=cluster_colors,
    startangle=90,
    wedgeprops=dict(width=0.6, edgecolor='white', linewidth=2),
    textprops={'fontsize': 9}
)

for autotext in autotexts:
    autotext.set_fontweight('bold')
    autotext.set_fontsize(10)

ax2.set_title('Distribusi Pengguna per Cluster', fontweight='bold')

# Tambah total di tengah donut
ax2.text(0, 0, f'Total\n{len(df_result):,}\nPengguna',
         ha='center', va='center', fontsize=11, fontweight='bold')

plt.tight_layout()
plt.savefig('/content/05_clustering_result.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Plot hasil clustering tersimpan!")

from matplotlib.patches import FancyArrowPatch
import matplotlib.gridspec as gridspec

cluster_means_norm = pd.DataFrame(
    scaler_mm.transform(df_result.groupby('Cluster')[features_available].mean()),
    columns=features_available
)

n_features = len(features_available)
angles = np.linspace(0, 2 * np.pi, n_features, endpoint=False).tolist()
angles += angles[:1]

fig, ax = plt.subplots(figsize=(10, 10), subplot_kw=dict(polar=True))

for cluster_id in range(OPTIMAL_K):
    values = cluster_means_norm.iloc[cluster_id].tolist()
    values += values[:1]

    label = engagement_labels.get(cluster_id, (f'Cluster {cluster_id}',))[0]
    color = cluster_colors[cluster_id]

    ax.plot(angles, values, 'o-', linewidth=2.5, label=label, color=color)
    ax.fill(angles, values, alpha=0.15, color=color)

ax.set_xticks(angles[:-1])
feature_labels_short = [f[:15] + '...' if len(f) > 15 else f for f in features_available]
ax.set_xticklabels(feature_labels_short, fontsize=9)

ax.set_ylim(0, 1)
ax.set_yticks([0.2, 0.4, 0.6, 0.8, 1.0])
ax.set_yticklabels(['0.2', '0.4', '0.6', '0.8', '1.0'], fontsize=7, alpha=0.7)

ax.set_title(' Radar Chart - Profil Engagement per Cluster\n(Fitur Gamifikasi & Pembelajaran)',
             fontsize=13, fontweight='bold', pad=20)
ax.legend(loc='upper right', bbox_to_anchor=(1.3, 1.1), fontsize=9)

plt.tight_layout()
plt.savefig('/content/06_radar_chart.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Radar chart tersimpan!")

from matplotlib import cm

fig, ax = plt.subplots(figsize=(10, 6))

silhouette_vals = silhouette_samples(X, cluster_labels)

y_lower = 10
for i in range(OPTIMAL_K):
    ith_cluster_silhouette_values = silhouette_vals[cluster_labels == i]
    ith_cluster_silhouette_values.sort()

    size_cluster_i = ith_cluster_silhouette_values.shape[0]
    y_upper = y_lower + size_cluster_i

    color = cluster_colors[i]
    ax.fill_betweenx(np.arange(y_lower, y_upper),
                     0, ith_cluster_silhouette_values,
                     facecolor=color, edgecolor=color, alpha=0.7)

    label = engagement_labels.get(i, (f'C{i}',))[0].split()[-1]
    ax.text(-0.05, y_lower + 0.5 * size_cluster_i, str(i))
    y_lower = y_upper + 10

ax.set_title(f' Silhouette Analysis - K-Means (k={OPTIMAL_K})\nSilhouette Score = {final_sil:.4f}',
             fontweight='bold')
ax.set_xlabel('Silhouette Coefficient')
ax.set_ylabel('Cluster')

ax.axvline(x=final_sil, color='red', linestyle='--', linewidth=2,
           label=f'Avg Silhouette = {final_sil:.4f}')
ax.legend()
ax.set_yticks([])

plt.tight_layout()
plt.savefig('/content/07_silhouette_analysis.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Silhouette analysis plot tersimpan!")

fig, axes = plt.subplots(1, 2, figsize=(16, 6))

ax1 = axes[0]
bar_colors = ['#e74c3c' if k == best_dbi_k else '#3498db' for k in results_df['k']]
bars = ax1.bar(results_df['k'], results_df['davies_bouldin'],
               color=bar_colors, edgecolor='white', linewidth=1.5,
               alpha=0.9)

for bar, val in zip(bars, results_df['davies_bouldin']):
    ax1.text(bar.get_x() + bar.get_width()/2., bar.get_height() + 0.01,
             f'{val:.3f}', ha='center', va='bottom', fontsize=8, fontweight='bold')

ax1.set_xlabel('Jumlah Cluster (k)', fontsize=12)
ax1.set_ylabel('Davies-Bouldin Index', fontsize=12)
ax1.set_title(f'Davies-Bouldin Index per Jumlah Cluster\n(Optimal: k={best_dbi_k}, DBI={min_dbi:.4f})',
              fontweight='bold')
ax1.set_xticks(results_df['k'])

from matplotlib.patches import Patch
legend_elements = [
    Patch(facecolor='#e74c3c', label=f'Optimal (k={best_dbi_k})'),
    Patch(facecolor='#3498db', label='Lainnya')
]
ax1.legend(handles=legend_elements)
ax1.grid(axis='y', alpha=0.3)

ax2 = axes[1]

def normalize_series(s, invert=False):
    n = (s - s.min()) / (s.max() - s.min())
    return 1 - n if invert else n

inertia_norm = normalize_series(results_df['inertia'], invert=True)
dbi_norm = normalize_series(results_df['davies_bouldin'], invert=True)
sil_norm = normalize_series(results_df['silhouette'])
ch_norm = normalize_series(results_df['calinski_harabasz'])

ax2.plot(results_df['k'], dbi_norm, 'ro-', linewidth=2, markersize=8, label='DBI (dinormalisasi, diinvert)')
ax2.plot(results_df['k'], sil_norm, 'gs-', linewidth=2, markersize=8, label='Silhouette')
ax2.plot(results_df['k'], ch_norm, 'b^-', linewidth=2, markersize=8, label='Calinski-Harabasz')
ax2.plot(results_df['k'], inertia_norm, 'm*-', linewidth=2, markersize=8, label='Inertia (diinvert)')

ax2.axvline(x=best_dbi_k, color='red', linestyle='--', alpha=0.7, label=f'k optimal = {best_dbi_k}')
ax2.set_xlabel('Jumlah Cluster (k)', fontsize=12)
ax2.set_ylabel('Score (ternormalisasi, semakin tinggi = semakin baik)', fontsize=10)
ax2.set_title('Perbandingan Semua Metrik Evaluasi\n(setelah normalisasi)', fontweight='bold')
ax2.legend(fontsize=9)
ax2.set_xticks(results_df['k'])
ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig('/content/08_davies_bouldin_detail.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Visualisasi Davies-Bouldin Index tersimpan!")

"""## Analisis Dampak Gamifikasi per Cluster"""

print("=" * 65)
print("    ANALISIS MENDALAM: DAMPAK GAMIFIKASI PER CLUSTER")
print("=" * 65)

for cluster_id in range(OPTIMAL_K):
    cluster_data = df_result[df_result['Cluster'] == cluster_id]
    label = engagement_labels.get(cluster_id, (f'Cluster {cluster_id}', ''))

    print(f"\n{'─' * 55}")
    print(f" CLUSTER {cluster_id}: {label[0]}")
    print(f"{'─' * 55}")
    print(f"   Jumlah Pengguna: {len(cluster_data):,} ({len(cluster_data)/len(df_result)*100:.1f}%)")
    print(f"\n    Statistik Fitur:")

    stats_cluster = cluster_data[features_available].describe().round(3)
    for feat in features_available[:5]:
        mean_val = cluster_data[feat].mean()
        std_val = cluster_data[feat].std()
        overall_mean = df_result[feat].mean()
        comparison = '↑' if mean_val > overall_mean else '↓'
        print(f"   {feat[:30]:30s}: {mean_val:.3f} ± {std_val:.3f} {comparison}")


print("\n" + "=" * 65)
print("    UJI STATISTIK: KRUSKAL-WALLIS (Non-Parametrik)")
print("   H₀: Tidak ada perbedaan signifikan antar cluster")
print("   H₁: Ada perbedaan signifikan antar cluster")
print("=" * 65)

for feat in features_available:
    groups = [df_result[df_result['Cluster'] == k][feat].values
              for k in range(OPTIMAL_K)]
    stat, p_val = kruskal(*groups)
    significance = ' Signifikan' if p_val < 0.05 else '❌ Tidak Signifikan'
    print(f"   {feat[:35]:35s}: H={stat:.3f}, p={p_val:.4f} → {significance}")

cluster_feature_means = df_result.groupby('Cluster')[features_available].mean()

fig, ax = plt.subplots(figsize=(16, 7))

n_features = len(features_available)
n_clusters = OPTIMAL_K
x = np.arange(n_features)
width = 0.8 / n_clusters

for i, cluster_id in enumerate(range(n_clusters)):
    offset = (i - n_clusters/2 + 0.5) * width
    label = engagement_labels.get(cluster_id, (f'Cluster {cluster_id}',))[0]
    bars = ax.bar(
        x + offset,
        cluster_feature_means.iloc[cluster_id],
        width=width * 0.9,
        label=label,
        color=cluster_colors[i],
        alpha=0.85,
        edgecolor='white',
        linewidth=0.5
    )

ax.set_xlabel('Fitur Engagement & Gamifikasi', fontsize=12)
ax.set_ylabel('Rata-rata Nilai', fontsize=12)
ax.set_title(' Perbandingan Rata-rata Fitur Gamifikasi & Engagement\nper Cluster Pengguna',
             fontsize=13, fontweight='bold')
ax.set_xticks(x)
feature_labels_short = [f[:12] + '...' if len(f) > 12 else f for f in features_available]
ax.set_xticklabels(feature_labels_short, rotation=30, ha='right')
ax.legend(loc='upper right', fontsize=9)
ax.grid(axis='y', alpha=0.3)

plt.tight_layout()
plt.savefig('/content/09_feature_comparison.png', dpi=150, bbox_inches='tight')
plt.show()
print(" Plot perbandingan fitur tersimpan!")

"""## Tabel Ringkasan & Laporan Akhir"""

print("=" * 75)
print("    LAPORAN AKHIR: K-MEANS CLUSTERING & DAVIES-BOULDIN INDEX")
print("   Investigating the Impact of Gamification in Online Learning Platforms")
print("=" * 75)

print(f"""
 KONFIGURASI EKSPERIMEN:
   Dataset    : Online Course Engagement Dataset (Kaggle)
   Sampel     : {len(df_result):,} pengguna
   Fitur      : {len(features_available)} fitur engagement & gamifikasi
   Algoritma  : K-Means Clustering (k-means++ initialization)
   Evaluasi   : Davies-Bouldin Index (primer), Silhouette, Calinski-Harabasz

 HASIL UTAMA:
   Jumlah Cluster Optimal    : k = {OPTIMAL_K}
   Davies-Bouldin Index      : {final_dbi:.4f} (lebih rendah = lebih baik)
   Silhouette Score          : {final_sil:.4f} (lebih tinggi = lebih baik)
   Calinski-Harabasz Score   : {final_ch:.2f} (lebih tinggi = lebih baik)
   Inertia (WCSS)            : {final_inertia:,.2f}

 INTERPRETASI DAVIES-BOULDIN INDEX:
   DBI = {final_dbi:.4f}
   → Mengukur rasio rata-rata dispersi intra-cluster terhadap
     separasi antar cluster
   → Nilai mendekati 0 menunjukkan cluster yang sangat kompak
     dan terpisah dengan baik
   → DBI < 1.0 umumnya dianggap sebagai hasil clustering yang baik
""")

print(" PROFIL CLUSTER PENGGUNA:")
print("-" * 75)

for cluster_id in range(OPTIMAL_K):
    label_info = engagement_labels.get(cluster_id, (f'Cluster {cluster_id}', 'N/A'))
    count = (df_result['Cluster'] == cluster_id).sum()
    pct = count / len(df_result) * 100

    print(f"\n  Cluster {cluster_id} [{label_info[0]}]")
    print(f"  Jumlah: {count:,} pengguna ({pct:.1f}%)")
    print(f"  {label_info[1] if len(label_info) > 1 else ''}")

print(f"""
 KESIMPULAN DAMPAK GAMIFIKASI:
   1. Platform e-learning dengan fitur gamifikasi berhasil menciptakan
      {OPTIMAL_K} kelompok pengguna yang berbeda secara signifikan
   2. DBI = {final_dbi:.4f} menunjukkan bahwa pengelompokan berhasil
      membentuk cluster yang terpisah dengan baik
   3. Terdapat perbedaan signifikan (p<0.05) antar cluster pada
      mayoritas fitur gamifikasi dan engagement
   4. Gamifikasi memiliki dampak berbeda-beda bergantung pada
      segmen pengguna, dengan pengguna aktif merespons lebih baik

 REFERENSI DATASET:
   • https://www.kaggle.com/datasets/rabieelkharoua/predict-online-course-engagement-dataset
   • https://www.kaggle.com/datasets/bismasajjad/online-learning-platform-engagement-dataset
""")

output_path = '/content/hasil_clustering_gamifikasi.csv'
df_result.to_csv(output_path, index=False)
print(f" Dataset hasil clustering tersimpan: {output_path}")

eval_path = '/content/evaluasi_cluster.csv'
results_df.to_csv(eval_path, index=False)
print(f" Tabel evaluasi tersimpan: {eval_path}")

profile_path = '/content/profil_cluster.csv'
cluster_feature_means.to_csv(profile_path)
print(f" Profil cluster tersimpan: {profile_path}")

print("\n Semua output yang dihasilkan:")
outputs = [
    '/content/01_EDA_distribusi.png',
    '/content/02_correlation_heatmap.png',
    '/content/03_boxplot_normalized.png',
    '/content/04_cluster_evaluation.png',
    '/content/05_clustering_result.png',
    '/content/06_radar_chart.png',
    '/content/07_silhouette_analysis.png',
    '/content/08_davies_bouldin_detail.png',
    '/content/09_feature_comparison.png',
    '/content/hasil_clustering_gamifikasi.csv',
    '/content/evaluasi_cluster.csv',
    '/content/profil_cluster.csv',
]

for f in outputs:
    if os.path.exists(f):
        size = os.path.getsize(f) / 1024
        print(f"    {os.path.basename(f)} ({size:.1f} KB)")
    else:
        print(f"     {os.path.basename(f)} - belum dibuat")

from google.colab import files
import zipfile

zip_path = '/content/hasil_penelitian_gamifikasi.zip'

with zipfile.ZipFile(zip_path, 'w', zipfile.ZIP_DEFLATED) as zipf:
    for f in outputs:
        if os.path.exists(f):
            zipf.write(f, os.path.basename(f))

print(f" File ZIP berhasil dibuat: {zip_path}")
print("\n⬇ Mengunduh file hasil penelitian...")
files.download(zip_path)
print(" Download selesai!")